name: "pr-validation"

on:
  pull_request:

permissions:
      checks: write
      contents: read
      pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  terraform:
    uses: schubergphilis/mcaf-github-workflows/.github/workflows/pr-validation.yml@main
