name: "release-drafter"

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - .github
      - .pre-commit-config.yaml
      - CHANGELOG.md
      - LICENSE
  workflow_dispatch:      

permissions:
      # write permission is required to create a github release
      contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
