name: "update-changelog"

on:
  release:
    types:
      - published
  workflow_dispatch:  
  
permissions:
      contents: write

jobs:
  terraform:
    uses: schubergphilis/mcaf-github-workflows/.github/workflows/update-changelog.yml@main
    secrets:
      mcaf-github-token: ${{ github.token }}
